<?php

namespace Revo\Sidecar\ExportFields;

use Carbon\Carbon;
use Illuminate\View\ComponentAttributeBag;
use Revo\Sidecar\Filters\Filters;

class DateTime extends Date
{
    protected $withSeconds = false;
    
    public function withSeconds($withSeconds = true) : self {
        $this->withSeconds = $withSeconds;
        return $this;
    }

    public function toHtml($row): string
    {
        return parent::toHtml($row); // TODO: Change the autogenerated stub
    }

    protected function nonGroupedValue($date, $forHtml = false) : string {
        if ($forHtml){
            return view('sidecar::fields.datetime', [
                'date' => $date,
                'withSeconds' => $this->withSeconds
            ])->render();
        }
        return $date->toDatetimeString();
    }
}