<?php

namespace Revo\Sidecar\ExportFields;

use Revo\Sidecar\Filters\Filters;

class Id extends ExportField
{
    public static function make($field = 'id', $title = null, $dependsOnField = null)
    {
        return parent::make($field, $title, $dependsOnField)->onGroupingBy('count');
    }

    public function getTitle(): string
    {
        if ((new Filters())->groupBy){
            return __(config('sidecar.translationsPrefix').'count');
        }
        return parent::getTitle(); // TODO: Change the autogenerated stub
    }
}