<?php

namespace Revo\Sidecar\ExportFields;

use Revo\Sidecar\Filters\Filters;
use Revo\Sidecar\Filters\GroupBy;
use function GuzzleHttp\Psr7\_parse_request_uri;

class Id extends Link
{
    public static function make($field = 'id', $title = null, $dependsOnField = null)
    {
        return parent::make($field, $title, $dependsOnField)->onGroupingBy('count');
    }

    public function getTitle(): string
    {
        if ((new Filters())->groupBy->isGrouping()){
            return __(config('sidecar.translationsPrefix').'count');
        }
        return parent::getTitle(); // TODO: Change the autogenerated stub
    }

    public function toHtml($row): string
    {
        if ((new Filters())->groupBy->isGrouping()){
            return $this->getValue($row);
        }
        return parent::toHtml($row);
    }
}